- name: install docker
  apt: name=linux-image-generic-lts-trusty update-cache=yes  state=installed
  ignore_errors: yes
  tags:
  - setup

- name: install docker
  apt: name=wget update-cache=yes  state=installed
  ignore_errors: yes
  tags:
  - setup


- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  tags:
  - setup

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false
  tags:
  - setup

- name: docker setup
  shell: wget -qO- https://get.docker.com/ | sh
  tags:
  - setup

- name: add in grp
  user: name=docker comment="Add docker" uid=1040 group=root
  tags:
  - setup

- name: intsall curl
  apt: name=curl state=present
  tags:
  - setup

- name: docker-py
  pip: name=docker-py state=present
  tags:
  - login

- name: Log into DockerHub
  sudo: yes
  docker_login:
   username: "{{ username }}"
   password: "{{ password }}"
   email: "{{email}}"
  tags:
  - login
